### PR TITLE
Survey editor v0.2

### LINKED ISSUE #35: Collapse fields

### LINKED ISSUE #36: Add fields

### LINKED ISSUE #37: Delete fields

### LINKED ISSUE #41: Copy and Paste fields

### LINKED ISSUE #43: Delete Surveys
Show a modal for confirmation!

### LINKED ISSUE #44: Add Surveys

### LINKED ISSUE #45: Duplicate Surveys

### LINKED ISSUE #46: Modal view
Usecases:
* Confirm? Yes/No
* Delete Survey
* Undo Changes
* Log out

### LINKED ISSUE #47: Validate config on publish and not on save (except for survey-id)
In my opinion the UX is better when a user can just leave stuff empty at first.

This also makes adding surveys ways easier since a blank template (except for the survey-id) can be saved as a template. Without this, a new survey template would have to be a valid config right away.

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
1. Collaps fields, close #35 - Now every survey will be initially rendered like this. One can expand and collapse all cards by clicking anywhere on the header (the colorbar).

localhost_3000_configuration_test

2. Add fields between any existing field, close #36 :
https://drive.google.com/file/d/1P6TkiD5-2ESgoBlDu02zDg5-FioIZmeD/view?usp=sharing

3. Delete fields, close #37 :
https://drive.google.com/file/d/16_zQ_lDpzS8Ac_WDSdJN18Ejm01fiFvH/view?usp=sharing

4. Copy and Paste fields :D, close #41
https://drive.google.com/file/d/1GcI-ypFRLEtYzqPqmdnB9271Uo2EsVAp/view?usp=sharing

I will actually leave drag and drop (#38) for later since copy and paste work very well.

5. Add a central modal view, close #46, which can be used for submenus, confirmations, and so on

fastsurvey-modal-view

6. The validation of survey fields now happens of publish rather than on every save, close #47 . By this a user can save any draft config as long as it has a valid identifier.

7. Add surveys, close #44

fastsurvey-add-survey-modal

8. Remove surveys, close #43

remove-survey-modal

9. Duplicating surveys is also possible now, close #45. Looks exactly like the new-survey-modal, just with different labels.

### CODE REVIEW

**Review by empicano — APPROVED** [review]
Good job, looks great! Thanks for the cool change-highlighting sneakpeeks 🚀 😜 

I'm a big fan of the collapsing fields, that way the user can keep the overview of long surveys a lot better! 👍

I've seen that you deferred implementing drag and drop, but looking at the sneakpeek-videos I had some ideas (for later on) on how we could use it. The collapsed fields would make it really easy to drag and drop things around, so maybe we could simplify adding new fields (1) and copy-pasting (2), by reducing (1) to a single button at the end of the survey editor (or multiple for the different kinds of fields), see my professional drawing for clarification 😄 : 

fastsurvey-idea-drawing

To add a field _between_ existing fields the user would need to add it at the bottom and drag it up, but we would save space and avoid the modal dialogue. For (2) we could apply the same principle, by adding a "duplicate" button to a field that copies it right below (and the user would move it around using drag and drop), thus avoiding the paste button between fields. What do you think?

Concerning 8.: My idea of archiving was to keep the configuration and the results, but delete the survey. The status message from the screenshot is a bit confusing 😄 Also, my initial idea was to do this in the background, so the user doesn't need to take the decision. Not set in stone though, did you have something else in mind?

**Comment by empicano** [comment]
Concerning 7.: We could avoid the modal dialogue if we directly jump into the configuration editor with some pre-generated values for the general settings, could that be easier to use?

**Comment by dostuffthatmatters** [comment]
Regarding deferring Drag and Drop: I actually implemented that field collapsing for drag and drop :D Basically: onMouseDown -> collapse all and startDrag. I will definitely implement drag and drop in the future! Very important! Coding drag and drop is not that difficult by itself, however it is a challenge not to produce a big mess in the codebase ^^ That's why I have left it open for now.

**Comment by dostuffthatmatters** [comment]
The idea with **one set of buttons on the bottom** is also a good option! We could save some space in the y-direction and have less "flickering" when moving the mouse around.

We do need a good working drag and drop for that though!

I got the idea with buttons inbetween fields from https://observablehq.com/@d3/learn-d3 - similiar to Jupyter Notebooks but for d3 :)

**Comment by dostuffthatmatters** [comment]
Regarding both 7 (avoid modal) and the add-button-placement: I don't know which is the best solution for either of those things. The decisions I took are really just personal preference.

I am already putting together a big list of UX stuff we will have to rethink again once all core features are in action :)

**Comment by dostuffthatmatters** [comment]
Regarding the **archiving message**: I was thinking that for every set of results a survey config must exist, and once a user archives a survey, it does not appear in the editor-list anymore (he can bring it back though).

We can also think about doing automatically. Or have this as an account setting: "Archive automatically after 2 weeks: yes/no" for example.

**Comment by empicano** [comment]
Sounds good! Good idea with the list, I have some topics with the backend where I‘m not sure on things, so that might be a good thing to write down as well until I find someone who can answer them.

I have a typo in my last comment: I wanted to write "My idea of archiving was to keep the configuration and the results, but delete the *submissions*." Makes more sense I hope 😄

**Pull request merged**
