### PR TITLE
Improve the design of the config editor a lot

### LINKED ISSUE #23: Clean up form UI a lot
Resources:

* https://refactoringui.com/
* https://www.youtube.com/watch?v=BMHUKij1yUE

### LINKED ISSUE #26: Submission Limit: Make postfix inline with input

### LINKED ISSUE #28: Fix z-index on dropdowns within form cards

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
Fix #23 , Fix #26 , Fix #28  and a lot more ...

**Old Design**: https://drive.google.com/file/d/1rTcShy6Vw5bsCyQoJU-b1F3aMSLCffck/view?usp=sharing

Improved design (but still cluttery): https://drive.google.com/file/d/1kgjWK7wvMEorg9EOVHiaei9nXoDaT4OE/view?usp=sharing

**New Design** with inlined hints: https://drive.google.com/file/d/1L6-ueuGroI3phryyrXBnayttnh9x1Ud2/view?usp=sharing

Additionally, inlining the text-input postfix (make the inputs more contextual): https://drive.google.com/file/d/1z17wG-VBvzg3Gi5LkEvQqF_kBc1LqEAE/view?usp=sharing

@empicano Any feedback is welcome!! :)

### CODE REVIEW

**Comment by dostuffthatmatters** [comment]
I also improved the authentication pages (login, etc.) a lot:
* A gray background for a better contrast against the white elevated inputs
* Inlining hints to reduce noise

**Review by empicano — APPROVED** [review]
Wow, massive improvements!! 🚀 😎 💯 
It makes a big difference that the fields don't move around anymore, good call!
And the short demos you made are really cool to see your progress!

I had two ideas:
- I think we can still improve the date input fields. Selecting day, month, etc. each from a dropdown seems a bit cumbersome to me. Those [date pickers from flight comparison sites](https://media.nngroup.com/media/editor/2016/11/28/02-expedia.png) are an option, but they're not very pretty and don't take the hour/minute into account. Maybe we could use [text fields](https://media.nngroup.com/media/editor/2016/11/28/09-countdown-timer.png) instead of dropdowns, what do you think?
- does the color a field configuration frame (the green ones) have meaning? We could make the frame color depend on the field type (e.g. red for email, blue for selection etc.), to let the user differentiate quicker between different fields.

**Comment by dostuffthatmatters** [comment]
@empicano 

I am really happy, that you like it! :) Still a lot work on in the future ^^

Regard the **datepicker**: See #33 :) We should definitely build a datepicker or some better solution soon!

Regarding the **colors**: I wanted to bring a little more color in there and these physical cards looked nice. They are all green as of right now - just a placeholder.

I was thinking about letting users choose a color theme, but your idea with one color per field sound really good!! And ist fast to implement :)

**Comment by dostuffthatmatters** [comment]
@empicano 

Here a version with distinct! We can definitely do a proper colortheme there, just didn't want to waste a lot of time just yet ^^

localhost_3000_configuration_test

**Comment by empicano** [comment]
Really cool, looks good! 🎉

**Pull request merged**
